### ISSUE TITLE
Issue with LL120 (or 8+/16 LED?) fans

### ISSUE THREAD

**Issue by eh** [bobrown101/linux-corsair-lighting-node-core-control#1]
I have a Node Core and 3 LL120 fans, these fans have 16 LEDs each. I can control fan 1 with
--numberFans 1 --ledsPerFan 16 --animation SCROLL

However specifying more fans (--numberFans 3 --ledsPerFan 16) only fan 1 and 8 LEDS on fan 2 will light, fan 3 does not light. The same is true for --numberFans 2. 

Worth noting, --numberFans 1 --ledsPerFan 17 will light all LEDs on fan 1 and 1 LED on fan 2.
also: --numberFans 1 --ledsPerFan 16 --animation STATIC --colors blue
lights only 8 LEDs on fan 1, maybe there's some clues here.

I'm guessing this is to do with how the packets are being split up, but I'm not up enough on JS to understand how it's doing what it's doing. I can add a bunch of console.log("Sending Packet: " + byteArray); output here if that would help.

**Comment by bobrown101** [comment]
I will look into it. 

Also, as a side note STATIC takes a color for each fan, so if you wanted one fan red, one fan green, and one fan blue you would do `—colors red green blue`

**Comment by eh** [comment]
Okay, thanks. I was mentioning STATIC as it's the only animation that won't light all 16 LEDs on fan 1 when using numberFans 1, only 8 light regardless of ledsPerFan. It behaves the same as the others with numberFans 3, all 16 on fan1 and 8 on fan2, nothing on 3.

**Comment by bobrown101** [comment]
So I think I might be on the right track here. Because I dont have access to LL120 fans Im going to need your help to verify I fixed the bug.

Could you please run the following and verify that all leds on one fan turn red, and that no other leds on any other fan turn on?
`yarn update && sudo yarn start --colors red --animation STATIC --period 80 --brightness 100 --ledsPerFan 16`

**Comment by eh** [comment]
Yes, looking good, both commands work as you describe.

**Comment by bobrown101** [comment]
Okay one last thing and I think we're all set

Please run `yarn update` and then test out the other animations. I have re-enabled them now

**Comment by eh** [comment]
There's a flash of white in TRANSITION when it hits blue, otherwise they all appear to be working correctly now.

**Comment by bobrown101** [comment]
I can re-create that bug locally so I will mark this issue as done and create a new one for that.

Thanks for the help!
