### ISSUE TITLE
issue compiling TypeScript

### ISSUE THREAD

**Issue by AnierinBliss** [bobrown101/linux-corsair-lighting-node-core-control#9]
TSError: ⨯ Unable to compile TypeScript:
controller.ts:63:3 - error TS2322: Type '[unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown]' is not assignable to type 'LightingNodeCore[]'.
  Type '{}' is missing the following properties from type 'LightingNodeCore': deviceID, manufacturer, product, rawDevice, and 2 more.

**Comment by sbec67** [comment]
Hi, i face the same Problem - how where u able to fix this ?
